package com.ecommerce.catalogservice.entity;


public enum OutboxEventType {
    PRODUCT_CREATED , PRICE_CHANGED , STOCK_CHANGED, PRODUCT_UPSERT,
    BRAND_UPSERT, CATEGORY_UPSERT,PRODUCT_RATING_UPDATED,
    PRODUCT_DELETED,
    REVIEW_CREATED , REVIEW_UPDATED
}
