spring:
  application:
    name: category-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8086/realms/ecobazar/protocol/openid-connect/certs
server:
  port: 8087
  forward-headers-strategy: FRAMEWORK
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}

jwt:
  client-id: identity-client
