spring:
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecobazar
    username: root
    password: 271201
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8086/realms/ecobazar/protocol/openid-connect/certs
server:
  port: 8087
  forward-headers-strategy: FRAMEWORK
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}

jwt:
  client-id: identity-client
